### ISSUE TITLE
README update - doesn't have all requirements

### ISSUE THREAD

**Issue by amcgail** [amcgail/louisvilleairmap.com#1]
First, the website depends on memcached. I just commented the code for that and it worked fine, but definitely worth a mention.

CKAN is giving me trouble now:

In trying to run the scraping script, specifically for the airnow data, CKAN is behaving badly. The ruby script consistently gets a “409: Conflict” when it tries to create a resource in CKAN, or when it’s trying to add data to an existing one. This is occurring in lib/tasks/ckan/aqs.rake:22, or if the resource exists it occurs on :107. It’s alright if you don’t know, but currently it’s preventing me from getting this set up.

The CKAN instance is at data.perscio.com

Thank you for your commitment, @marks

**Comment by marks** [comment]
@amcgail any possibility of me getting admin access to data.perscio.com? Not looking for SSH level login or anything just promotion of my ckan account ("skram") to admin?

Instructions to do this can be found at http://docs.ckan.org/en/latest/maintaining/getting-started.html?highlight=promote

---

So far, it looks like the data sets got created but the resources have not been.

Mark

**Comment by marks** [comment]
Looks like you need to update your ENV variables to have your CKAN_AQS_DATASET_ID to be `load-air-quality-system-aqs`

**TODO** Make that clear in README - that DATASET_IDs must be synched between CKAN and the config file

**Comment by marks** [comment]
You might have gotten past that issue - I just got to your 409 issue on line 22 of aqs.rake too now. It's having an issue creating a resource under the data set. I'd take a look at the CKAN logs.

**Comment by amcgail** [comment]
I'll do that. Yes, they are synced on my local version, didn't want to put that name in the README because I was merging with yours. I'll check the logs Monday, thank you for your effort.

**Comment by amcgail** [comment]
I'm back on this issue, after a bit of a break. I can't get into my CKAN per command line. I used a quick-start AWS AMI, so I'll just make it from scratch for a next step so I can actually diagnose these issues. Doubt it's that hard. The website failed initially because there is no jquery.js or underscore.js in public/vendor/recline/vendor/[etc]. I just created the directories and put them in myself. I'm guessing you used a tool to get these, so again maybe this is something that should be in the README

**Comment by marks** [comment]
Sorry, try running the following from the command line inside your git repo:

`git submodule init`
`git submodule update`

This should bring in the git submodules.

If this does work for you, LMK and I'll update the README (or you could submit a PR)

**Comment by amcgail** [comment]
That did the trick! Really wasn’t a hard fix on my side, so no worries.
I’ll let you know if there is anything else I run into, but it seems the only thing lacking now is a functioning CKAN

**Comment by marks** [comment]
Just added this info into the README at https://github.com/marks/louisvilleairmap.com/commit/f056da654df209b03f69ba9b71bf5602315462f3
